ddl
"CREATE TABLE activities (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  inquiry_id uuid,
  fleet_id uuid,
  source_id uuid,
  actor_user_id uuid,
  activity_type text NOT NULL,
  title text NOT NULL,
  description text,
  metadata jsonb NOT NULL,
  created_at timestamp with time zone NOT NULL
);"
"CREATE TABLE availability (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  fleet_id uuid NOT NULL,
  source_id uuid,
  external_id text,
  start_date date NOT NULL,
  end_date date NOT NULL,
  status text NOT NULL,
  location text,
  region text,
  embarkation_port text,
  disembarkation_port text,
  weekly_rate numeric(14,2),
  currency text NOT NULL,
  notes text,
  raw_data jsonb NOT NULL,
  source_updated_at timestamp with time zone,
  last_synced_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL
);"
"CREATE TABLE availability_checks (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  inquiry_id uuid NOT NULL,
  yacht_id uuid NOT NULL,
  source text NOT NULL,
  status text NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  checked_at timestamp with time zone NOT NULL,
  checked_by uuid,
  notes text,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL
);"
"CREATE TABLE charter_concierge_items (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  charter_id uuid NOT NULL,
  category text NOT NULL,
  title text NOT NULL,
  description text,
  status text NOT NULL,
  priority text NOT NULL,
  scheduled_at timestamp with time zone,
  location text,
  vendor_name text,
  vendor_contact text,
  estimated_cost numeric(14,2),
  currency text NOT NULL,
  source text NOT NULL,
  client_visible boolean NOT NULL,
  notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  assigned_to uuid,
  assigned_by uuid,
  assigned_at timestamp with time zone,
  due_at timestamp with time zone,
  guest_portal_id uuid,
  guest_request_key text
);"
"CREATE TABLE charter_guests (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  charter_id uuid NOT NULL,
  full_name text NOT NULL,
  guest_role text NOT NULL,
  is_primary boolean NOT NULL,
  email text,
  phone text,
  nationality text,
  date_of_birth date,
  passport_status text NOT NULL,
  passport_country text,
  passport_expiry date,
  dietary_requirements text,
  allergies text,
  accessibility_notes text,
  arrival_airport text,
  arrival_flight text,
  arrival_at timestamp with time zone,
  arrival_transfer_notes text,
  departure_airport text,
  departure_flight text,
  departure_at timestamp with time zone,
  departure_transfer_notes text,
  cabin_preference text,
  bed_preference text,
  notes text,
  profile_status text NOT NULL,
  sort_order integer NOT NULL,
  created_by uuid,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL
);"
"CREATE TABLE charter_itineraries (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  charter_id uuid NOT NULL,
  title text NOT NULL,
  status text NOT NULL,
  cruising_speed_knots numeric(8,2),
  fuel_burn_lph numeric(12,2),
  fuel_price_per_liter numeric(12,4),
  fuel_currency text NOT NULL,
  contingency_percent numeric(7,3) NOT NULL,
  notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL
);"
"CREATE TABLE charter_itinerary_activities (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  itinerary_id uuid NOT NULL,
  charter_id uuid NOT NULL,
  day_id uuid NOT NULL,
  position integer NOT NULL,
  activity_type text NOT NULL,
  title text NOT NULL,
  start_time time without time zone,
  end_time time without time zone,
  location text,
  description text,
  status text NOT NULL,
  guest_visible boolean NOT NULL,
  created_by uuid,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL
);"
"CREATE TABLE charter_itinerary_days (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  itinerary_id uuid NOT NULL,
  charter_id uuid NOT NULL,
  position integer NOT NULL,
  charter_date date NOT NULL,
  title text NOT NULL,
  destination_name text,
  overnight_type text NOT NULL,
  overnight_name text,
  summary text,
  guest_notes text,
  internal_notes text,
  guest_visible boolean NOT NULL,
  created_by uuid,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL
);"
"CREATE TABLE charter_itinerary_legs (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  itinerary_id uuid NOT NULL,
  charter_id uuid NOT NULL,
  position integer NOT NULL,
  charter_date date,
  from_name text NOT NULL,
  to_name text NOT NULL,
  from_lat numeric(10,7),
  from_lon numeric(10,7),
  to_lat numeric(10,7),
  to_lon numeric(10,7),
  distance_nm numeric(12,3),
  distance_source text NOT NULL,
  departure_time time without time zone,
  arrival_time time without time zone,
  cruising_speed_knots numeric(8,2),
  fuel_burn_lph numeric(12,2),
  fuel_price_per_liter numeric(12,4),
  guest_visible boolean NOT NULL,
  notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL
);"
"CREATE TABLE charter_itinerary_shares (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  charter_id uuid NOT NULL,
  itinerary_id uuid NOT NULL,
  token text NOT NULL,
  is_active boolean NOT NULL,
  hero_image_url text,
  published_at timestamp with time zone NOT NULL,
  expires_at timestamp with time zone,
  view_count integer NOT NULL,
  last_viewed_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL
);"
"CREATE TABLE charter_payment_schedule (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  charter_id uuid NOT NULL,
  payment_type text NOT NULL,
  label text,
  amount numeric(14,2) NOT NULL,
  currency text NOT NULL,
  due_date date,
  status text NOT NULL,
  amount_paid numeric(14,2) NOT NULL,
  paid_at timestamp with time zone,
  payment_reference text,
  notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL
);"
"CREATE TABLE charters (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  proposal_id uuid NOT NULL,
  confirmation_id uuid NOT NULL,
  proposal_yacht_id uuid,
  fleet_id uuid,
  reference text NOT NULL,
  client_name text NOT NULL,
  client_email text,
  client_phone text,
  yacht_name text NOT NULL,
  start_date date,
  end_date date,
  destination text,
  embarkation_port text,
  disembarkation_port text,
  guests integer,
  currency text NOT NULL,
  charter_fee numeric(14,2),
  vat_percent numeric(7,3),
  vat_amount numeric(14,2),
  apa_percent numeric(7,3),
  apa_amount numeric(14,2),
  deposit_percent numeric(7,3),
  deposit_amount numeric(14,2),
  balance_amount numeric(14,2),
  total_contract_value numeric(14,2),
  charter_status text NOT NULL,
  contract_status text NOT NULL,
  payment_status text NOT NULL,
  contract_sent_at timestamp with time zone,
  contract_signed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  cancelled_by uuid,
  cancellation_reason text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL
);"
"CREATE TABLE clients (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  name text NOT NULL,
  email text,
  phone text,
  status text NOT NULL,
  vip_level text NOT NULL,
  preferred_destination text,
  preferred_yacht_type text,
  notes text,
  preferences jsonb NOT NULL,
  lifetime_value numeric NOT NULL,
  last_contacted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL
);"
"CREATE TABLE companies (
  id uuid NOT NULL,
  name text NOT NULL,
  slug text NOT NULL,
  logo_url text,
  website_url text,
  contact_email text,
  contact_phone text,
  default_currency text NOT NULL,
  timezone text NOT NULL,
  subscription_status text NOT NULL,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  operating_model text,
  primary_market text,
  yacht_access_band text,
  onboarding_completed_at timestamp with time zone,
  onboarding_version integer NOT NULL
);"
"CREATE TABLE company_members (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text NOT NULL,
  created_at timestamp with time zone NOT NULL
);"
"CREATE TABLE data_sources (
  id uuid NOT NULL,
  name text NOT NULL,
  source_type text NOT NULL,
  source_url text,
  file_name text,
  status text NOT NULL,
  sync_frequency_minutes integer NOT NULL,
  last_synced_at timestamp with time zone,
  last_sync_status text,
  last_sync_message text,
  yacht_count integer NOT NULL,
  availability_count integer NOT NULL,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  company_id uuid NOT NULL,
  external_reference text,
  configuration jsonb NOT NULL,
  credentials_reference text,
  sync_cursor text,
  error_count integer NOT NULL,
  next_sync_at timestamp with time zone,
  is_active boolean NOT NULL
);"
"CREATE TABLE documents (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  fleet_id uuid,
  inquiry_id uuid,
  source_id uuid,
  document_type text NOT NULL,
  name text NOT NULL,
  file_name text,
  storage_bucket text,
  storage_path text,
  public_url text,
  mime_type text,
  file_size_bytes bigint,
  extracted_text text,
  metadata jsonb NOT NULL,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  client_id uuid,
  proposal_id uuid,
  category text,
  file_size bigint,
  version integer,
  status text,
  charter_id uuid
);"
"CREATE TABLE email_connections (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  provider text NOT NULL,
  provider_account_id text,
  email_address text NOT NULL,
  access_token_encrypted text NOT NULL,
  refresh_token_encrypted text NOT NULL,
  token_expires_at timestamp with time zone,
  scopes text[] NOT NULL,
  status text NOT NULL,
  created_by uuid,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  last_used_at timestamp with time zone
);"
"CREATE TABLE email_drafts (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  inquiry_id uuid,
  fleet_id uuid,
  manager_contact_id uuid,
  purpose text NOT NULL,
  to_email text NOT NULL,
  to_name text,
  subject text NOT NULL,
  body text NOT NULL,
  start_date date,
  end_date date,
  status text NOT NULL,
  provider text,
  external_message_id text,
  external_thread_id text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  sent_at timestamp with time zone
);"
"CREATE TABLE fleet (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  source_id uuid,
  external_id text,
  source_row_reference text,
  name text NOT NULL,
  slug text,
  yacht_type text,
  builder text,
  model text,
  build_year integer,
  refit_year integer,
  length_meters numeric(8,2),
  beam_meters numeric(8,2),
  draft_meters numeric(8,2),
  guest_capacity integer,
  sleeping_guests integer,
  cruising_guests integer,
  cabin_count integer,
  crew_count integer,
  home_port text,
  cruising_regions text[] NOT NULL,
  weekly_rate_low numeric(14,2),
  weekly_rate_high numeric(14,2),
  currency text NOT NULL,
  amenities text[] NOT NULL,
  description text,
  hero_image_url text,
  brochure_url text,
  status text NOT NULL,
  is_featured boolean NOT NULL,
  raw_data jsonb NOT NULL,
  source_updated_at timestamp with time zone,
  last_synced_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  cruising_speed_knots numeric,
  fuel_consumption_lph numeric,
  flag text,
  low_season_rate numeric,
  high_season_rate numeric,
  standard_rate_currency text,
  default_apa_percent numeric,
  profile_updated_at timestamp with time zone
);"
"CREATE TABLE guest_portals (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  charter_id uuid NOT NULL,
  token_hash text,
  token_hint text,
  status text NOT NULL,
  expires_at timestamp with time zone,
  sent_at timestamp with time zone,
  opened_at timestamp with time zone,
  opened_count integer NOT NULL,
  submitted_at timestamp with time zone,
  preferences jsonb NOT NULL,
  created_by uuid,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  token_encrypted text
);"
"CREATE TABLE inquiries (
  id uuid NOT NULL,
  reference text NOT NULL,
  client_name text NOT NULL,
  client_type text,
  email text,
  phone text,
  destination text,
  start_date date,
  end_date date,
  guests integer,
  budget_min numeric,
  budget_max numeric,
  currency text,
  preferences text,
  original_inquiry text,
  source text,
  status text,
  extraction_confidence integer,
  close_probability integer,
  past_inquiries integer,
  past_bookings integer,
  missing_information text[],
  suggested_question text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  company_id uuid NOT NULL,
  assigned_to uuid,
  metadata jsonb NOT NULL,
  yacht_id uuid,
  yacht_name text,
  weekly_rate numeric,
  proposal_status text,
  proposal_pdf text,
  proposal_created_at timestamp with time zone,
  proposal_sent_at timestamp with time zone,
  pdf_generated_at timestamp with time zone,
  pdf_version integer NOT NULL,
  pdf_status text NOT NULL,
  client_id uuid
);"
"CREATE TABLE notifications (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  user_id uuid,
  type text NOT NULL,
  title text NOT NULL,
  message text,
  href text,
  entity_type text,
  entity_id uuid,
  priority text NOT NULL,
  read_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL
);"
"CREATE TABLE proposal_assets (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  fleet_id uuid,
  document_id uuid,
  asset_type text NOT NULL,
  title text,
  storage_bucket text,
  storage_path text,
  public_url text,
  sort_order integer NOT NULL,
  width integer,
  height integer,
  alt_text text,
  metadata jsonb NOT NULL,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL
);"
"CREATE TABLE proposal_client_events (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  proposal_id uuid NOT NULL,
  share_link_id uuid,
  event_type text NOT NULL,
  proposal_yacht_id uuid,
  fleet_id uuid,
  metadata jsonb NOT NULL,
  created_at timestamp with time zone NOT NULL
);"
"CREATE TABLE proposal_client_selections (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  proposal_id uuid NOT NULL,
  proposal_yacht_id uuid NOT NULL,
  share_link_id uuid,
  fleet_id uuid,
  yacht_name text NOT NULL,
  selected_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL
);"
"CREATE TABLE proposal_confirmations (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  proposal_id uuid NOT NULL,
  proposal_yacht_id uuid,
  fleet_id uuid,
  confirmation_type text NOT NULL,
  status text NOT NULL,
  requested_at timestamp with time zone,
  requested_by uuid,
  confirmed_at timestamp with time zone,
  confirmed_by uuid,
  declined_at timestamp with time zone,
  declined_by uuid,
  cancelled_at timestamp with time zone,
  cancelled_by uuid,
  contact_name text,
  contact_email text,
  notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL
);"
"CREATE TABLE proposal_share_links (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  proposal_id uuid NOT NULL,
  token_hash text NOT NULL,
  is_active boolean NOT NULL,
  expires_at timestamp with time zone,
  revoked_at timestamp with time zone,
  last_opened_at timestamp with time zone,
  opened_count integer NOT NULL,
  created_by uuid,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL
);"
"CREATE TABLE proposal_yachts (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  proposal_id uuid NOT NULL,
  fleet_id uuid,
  position smallint NOT NULL,
  yacht_name text NOT NULL,
  weekly_rate numeric,
  estimated_total numeric,
  currency text NOT NULL,
  broker_note text,
  availability_status text NOT NULL,
  verification_status text NOT NULL,
  access_type text,
  calendar_authority text,
  booking_model text,
  snapshot jsonb NOT NULL,
  created_by uuid,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL
);"
"CREATE TABLE yacht_access_profiles (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  fleet_id uuid NOT NULL,
  access_type text NOT NULL,
  calendar_authority text NOT NULL,
  booking_model text NOT NULL,
  client_proposal_permission boolean NOT NULL,
  public_listing_permission boolean NOT NULL,
  notes text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL
);"
"CREATE TABLE yacht_cabin_configuration (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  fleet_id uuid NOT NULL,
  cabin_type text NOT NULL,
  cabin_count integer NOT NULL,
  position integer NOT NULL,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL
);"
"CREATE TABLE yacht_contacts (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  fleet_id uuid NOT NULL,
  management_company text,
  contact_name text,
  role text NOT NULL,
  email text NOT NULL,
  phone text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL
);"
"CREATE TABLE yacht_images (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  fleet_id uuid NOT NULL,
  storage_path text NOT NULL,
  image_url text NOT NULL,
  category text NOT NULL,
  is_hero boolean NOT NULL,
  position integer NOT NULL,
  alt_text text,
  created_by uuid,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL
);"
"CREATE TABLE yacht_toys (
  id uuid NOT NULL,
  company_id uuid NOT NULL,
  fleet_id uuid NOT NULL,
  name text NOT NULL,
  position integer NOT NULL,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL
);"